# Generated by Django 2.2.5 on 2019-11-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20191027_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='Описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='1', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
