# Generated by Django 2.2.5 on 2019-11-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20191110_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='1', upload_to='books/images/'),
        ),
    ]
