# Generated by Django 2.2.5 on 2019-11-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191112_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='1', upload_to='media/books/images'),
        ),
    ]
